SELECT
    UserNum as userNum,
    ID as id,
    Password as password,
    Login as login,
    LoginTime as loginTime,
    LogoutTime as logoutTime,
    AuthType as authType,
    PlayTime as playTime,
    IdentityNo as identityNo,
    LoginEx as loginEx,
    LastIp as lastIp,
    AuthKey as authKey,
    nation_Code as nationCode,
    createDate as createDate,
    Email as email,
    IP as ip,
    Question as question,
    Answer as answer,
    LoginCounter as loginCounter,
    Chave as authKey,
    QtHackerSkill as qtHackerSkill,
    Nome as name,
    Sobrenome as lastName,
    Cidade as city,
    UF as uf,
    Enquete as survey,
    Reset as reset,
    Hash as hash,
    TempoBan as banTime,
    Perg as perg
FROM cabal_auth_table
WHERE ID = :username;